### ISSUE TITLE
can't compile on Arch Linux

### ISSUE THREAD

**Issue by CaioVdmm** [TASVideos/desmume#304] opened 2019-10-17 02:44 UTC
I can't compile Desmume on arch Linux but i can compile the desmume reload so its desmume bug in the sources.
i get this error below:
`/usr/include/glib-2.0/glib/gmacros.h:988:33: error: missing binary operator before token "_Pragma"
  988 | #define _GLIB_GNUC_DO_PRAGMA(x) _Pragma(G_STRINGIFY (x))`
this error is related of main.cpp.
and i say again, i can compile the desmume reload and its ha a source of desmume from 2018

**Comment by zeromus** [comment] 2019-10-17 02:49
duplicate of #302

**Comment by FunkyQChicken** [comment] 2019-11-21 15:46
This is a hacky fix, and I don't recommend it if you don't know what you are doing. But, you can get it to compile and run by changing the line in the file ("/usr/include/ ... /gmacros.h") from 
```cpp
#define _GLIB_GNUC_DO_PRAGMA(x) _Pragma(G_STRINGIFY (x))
```
to

**Comment by shibotto** [comment] 2019-12-13 22:16
So I was looking around and I found this page on [GCC manual](https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html), in particular:

> The standard is unclear on where a _Pragma operator can appear. The preprocessor does not accept it within a preprocessing conditional directive like ‘#if’. To be safe, you are probably best keeping it out of directives other than ‘#define’, and putting it on a line of its own. 

It seems relevant to me. I'm not versed in C/C++, especially preprocessor stuff, but can all the `#if !g_thread_supported()` be converted to standard if?

My log was [here](https://github.com/TASVideos/desmume/issues/305#issuecomment-559840814).

Also @CaioVdmm I think one of the issues reporting this problem can safely be reopened, since it's been confirmed by 3 different users so far.

**Comment by zeromus** [comment] 2019-12-13 22:36
3 different users are using a version of archlinux shipping with a broken version of glib
in the other thread, we have a log that shows that the function desmume is using was intentionally broken by glib.
Find out if GLIB_VERSION_MIN_REQUIRED is defined and see if defining it to an old version helps (see what glib version was current when the glib files in desmume were last edited)

**Comment by shibotto** [comment] 2019-12-13 23:38
OK, I tracked it down to bf3e1b1cf338e2e276a91840757e9bc194417504 and reverting fixed it for me. Last working GLib with that commit is 2.60.7 (not so old actually).
Either if this is really a broken feature or simply something you don't agree with, could you please put a warning in the README that your last supported GLib version is 2.60.7? This was extremely time consuming for me to sort out a problem you were already aware of.

**Comment by zeromus** [comment] 2019-12-14 00:14
open a PR to revert that and I'll push it.

**Comment by zeromus** [comment] 2020-01-20 21:15
fixed by recent pr

**Closed by zeromus** 2020-01-20 21:15 UTC
