### ISSUE TITLE
Zelda - Phantom Hourglass (E) - Flickering of Title Screen.

### ISSUE THREAD

**Issue by Papermanzero** [TASVideos/desmume#33] opened 2017-01-08 15:50 UTC
In the newest build the Title screen started to filcker (main screen and sub screen are changing regularly).
The latest build which I used and which did not have the issue was:
https://github.com/TASVideos/desmume/commit/f50f9d38fd462b1f66efa3eee2611237165bdb18

**Comment by Papermanzero** [comment] 2017-01-08 16:35
Here is the config, which can reproduce the issue.
A new config has not the problem.

[desmume.txt](https://github.com/TASVideos/desmume/files/692275/desmume.txt)

**Comment by rogerman** [comment] 2017-01-09 05:04
The config you provided has an LCDsSwap value of 2. This is equivalent to choosing the "View > LCDs Layout >Main screen first" menu option.

The reason why the title screen in Zelda: PH is swapping screens every frame is because this game uses dual screen 3D rendering. This style of rendering makes the main GPU engine render 3D once on the main display for every odd frame, and then render 3D once on the touch display for every even frame. When you use the Main Screen First option, this option causes the output of the main GPU engine to ALWAYS be displayed on the main display, regardless of its true destination. This feature can be pretty useless for most end-users, but can be a valuable debugging tool for developers that need to track the output of the main GPU engine on a per-frame basis.

Closing, since this is intended behavior, and not an actual bug.

**Closed by rogerman** 2017-01-09 05:04 UTC
Labels: invalid

**Comment by zeromus** [comment] 2017-01-09 05:11
for the sake of completeness, the same bug manifests on the referenced revision once the poor choice of LCDs layout is made.
