### ISSUE TITLE
[OpenGL]Fog rendering glitches after changing 3d settings or loading savestates.

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#247] opened 2019-01-16 09:09 UTC
When changing a 3d setting or loading a savestate while in an area with fog, black outlines (with MSAA enabled) can be seen and certain parts don't have fog rendered. Moving around causes an effect which looks like it's overwriting certain parts (didn't occur before 21a3fae).

Working:
![working](https://user-images.githubusercontent.com/1760158/51237510-88680380-19af-11e9-8688-1d73a05d23a5.JPG)
After changing settings:
![aftersetting](https://user-images.githubusercontent.com/1760158/51237516-8aca5d80-19af-11e9-9926-3e4e44fc84c8.JPG)
Moving after changing settings:
![movingaftersetting](https://user-images.githubusercontent.com/1760158/51237523-8c942100-19af-11e9-9b61-499dd92085cf.JPG)

Video: https://youtu.be/vmLKBgJGf9Q?t=5

RX570, 19.1.1 driver.
[desmume.ini.txt](https://github.com/TASVideos/desmume/files/2762399/desmume.ini.txt)

**Comment by rogerman** [comment] 2019-01-16 09:19
Cannot reproduce this issue in other games that use Fog rendering.

Please provide this game's ROM Name and ROM Serial. I will also need the .dsv Battery file for troubleshooting purposes.

**Comment by Jules-A** [comment] 2019-01-16 11:31
Pokemon Platinum
ROM serial: NTR-CPUE-USA

[Saves.zip](https://github.com/TASVideos/desmume/files/2763940/Saves.zip)

**Comment by rogerman** [comment] 2019-01-17 01:10
Commit 0dab591 addresses the issue where the fogged white area in the background was incorrectly being colored when moving around.

So as for the black outline caused by MSAA...

What's happening here is that the 3D layer is being composited on top of a 2D layer, where at this point, the 3D layer needs to be blended with the 2D layer using the 2D engine's rules. In this case, the white background is actually a 2D layer. The 3D layer is using the Fog effect to blend the far polygons seamlessly into the white 2D layer beneath it.

Okay, so now the technical explanation begins.

When the NDS renders Fog in the 3D layer, it is actually doing a one-time post-process pass over the entire framebuffer rather than determining the fogged fragment color directly in the rasterization process. Put another way, the particular fragments that are to be affected by the Fog pass are determined in the rasterization process, and then the Fog effect is applied to just those fragments in a separate pass.

Now... when MSAA is enabled, OpenGL determines which fragments should be fogged using the non-resolved MSAA version of the framebuffer. However, when OpenGL does the Fog pass, our OpenGL renderer does the pass AFTER the framebuffer has already been resolved. Unfortunately, the "fogged fragment flag" is assumed to be boolean (either ON or OFF), and so the MSAA resolve can cause this flag to be set to some value between 0.0 and 1.0. Our Fog pass assumes that any fogged fragment flag with a value below 0.999 to treat the fragment as NOT fogged. In short, **when MSAA is enabled, any fogged fragment at a polygon edge should be assumed to have an undefined fog color.**

(If you're wondering why we perform the Fog pass on the post-resolved framebuffer -- it's a performance issue. The Fog pass is quite expensive as it is, and doing the Fog pass on the pre-resolved framebuffer would make the Fog pass excruciatingly slow, as well as adding the requirement to perform the Edge Mark on the pre-resolved framebuffer too. Just trust me that it is better to perform these passes on the post-resolved framebuffer.)

Also keep in mind that the NDS has no concept of MSAA, and so when compositing the 3D layer onto a 2D layer, the NDS assumes that polygon edges won't have any unexpected translucent fragments. However, during the MSAA resolve, OpenGL can generate unexpected translucent fragments. This means that if the 3D layer is composited onto a 2D layer that is not expecting any translucent fragments at the polygon edges, then halos can occur at these edges. In short, **when MSAA is enabled, any polygon edges that are composited onto a 2D layer should be assumed to have an undefined color.**

And so my position on this matter of the glitched black outline while using MSAA is this: **Applying MSAA onto a scene that was never designed to handle MSAA is a user issue. It should be the user's responsibility to judge whether any graphical glitches that result from using MSAA are acceptable. Therefore, I will not go out of my way to fix this glitch, since actually fixing this glitch would involve a complicated performance-killing heuristic that would have to be applied in both the 2D engine and the 3D renderer.**

**Comment by rogerman** [comment] 2019-01-17 02:38
`While what you said doesn't exactly explain why savestates and changing settings causes the black lines while normally exploring doesn't, I can make some better assumptions as to why.`

Well that one is easy -- it's because the OpenGL renderer was clearing the wrong buffer when Edge Mark was disabled and Fog was enabled. In this case, that "wrong buffer" was the Fog attributes buffer. Save states and changing settings easily reveal the incorrectly cleared buffer via a visual glitch. This was a regression introduced by commit 21a3fae and fixed in commit 0dab591.

**Closed by rogerman** 2019-01-17 02:38 UTC

**Comment by Jules-A** [comment] 2019-01-17 03:02
Hmm... I just tested 0dab591, it actually breaks the fog from rendering correctly when exploring normally which is more important than fixing the fog from rendering incorrectly when using savestates/changing settings.

**Comment by rogerman** [comment] 2019-01-17 05:13
> It actually breaks the fog from rendering correctly

Um... what? Fog seems to be working fine for me. See the screenshots.

![20190116_21-10-22 564 s mario64ds](https://user-images.githubusercontent.com/6055122/51296979-523c7b00-19d3-11e9-813f-9bbd1244aebf.png)
![20190116_21-09-12 815 spirittracks](https://user-images.githubusercontent.com/6055122/51296978-51a3e480-19d3-11e9-9e49-647d97926ce8.png)
![20190116_21-06-52 099 pokemon pl](https://user-images.githubusercontent.com/6055122/51296977-51a3e480-19d3-11e9-9f64-3770af642774.png)

All screenshots have MSAA disabled. Mario 64 uses Fog, Zelda:ST uses Fog and Edge Mark, and your save state of Pokemon Platinum uses Fog (I disabled Edge Mark here).

**Comment by Jules-A** [comment] 2019-01-17 05:20
With MSAA enabled I mean, for now I've just done 
> if (this->_enableFog && !this->_enableMultisampledRendering)
in
> Render3DError OpenGLRenderer_3_2::ClearUsingValues

since it renders correctly in that scene when not clearing fog. What are the consequences of not clearing?

**Comment by rogerman** [comment] 2019-01-17 05:37
I don't see any problems with Fog rendering while using MSAA. Including Mario 64 and Zelda:ST, which I retested with MSAA enabled, here are some more examples using MSAA and Fog.

![20190116_21-24-17 335 pszero](https://user-images.githubusercontent.com/6055122/51297585-b7916b80-19d5-11e9-98ee-5c9e9175d6ac.png)
![20190116_21-25-48 477 sekaijyu3](https://user-images.githubusercontent.com/6055122/51297587-b7916b80-19d5-11e9-9238-a0bc9873663c.png)
![20190116_21-26-30 838 dementium01](https://user-images.githubusercontent.com/6055122/51297589-b82a0200-19d5-11e9-9302-bf4c4d2867f6.png)
![20190116_21-27-12 512 pokemon pl](https://user-images.githubusercontent.com/6055122/51297588-b82a0200-19d5-11e9-833c-615a333ecb96.png)

Of course, the Pokemon Platinum screenshot has that black line glitch as before, but I have already explained exactly why this happens in the above post, and why I am unwilling to fix this particular glitch.

> What are the consequences of not clearing other than the issues I mentioned in this issue?

The consequences are that the previous frame's fog attributes will be carried over into the current frame's fog attributes, which is definitely incorrect behavior.

Why are you even using MSAA in Pokemon Platinum, anyways? Such a game, which already uses Edge Mark and is very dependent on 2D sprites rendered onto 3D quad polygons, won't benefit from MSAA anyways. While there are many other fully 3D games that can fully benefit from the smoothing improvements of MSAA, Pokemon Platinum definitely isn't one of them.

**Comment by Jules-A** [comment] 2019-01-17 05:55
Oh I see, so just it's just that rare-ish scene then, hmm.
As to why MSAA over Edge Mark in Plat, I guess I'm much more sensitive to aliasing than most people. Even in a game that doesn't doesn't benefit much from MSAA, I can't help but notice it and easily get annoyed by it. What I mainly have an issue with is the shimmering which even 2x MSAA is enough to solve, sure Edge Marking does a decent job for jaggies in Platinum but it doesn't stop the shimmering one bit. Even if I were to use Edge Marking, when it comes to fog it suffers the same issue anyways.

**Comment by rogerman** [comment] 2019-01-17 06:12
I'm positive that the glitched black line that is the result of MSAA's interaction with a 2D layer below IS the "correct" behavior as far as the OpenGL renderer is concerned.

In reality, when you run MSAA, any games that render 3D polygon edges against 2D layers should consistently have this same type of glitch. In all of my testing, this has been the case so far. I honestly don't how your first screenshot was able to render in MSAA without the glitched black line, but I'm pretty sure that it is "wrong" according to our OpenGL renderer.

**Comment by Jules-A** [comment] 2019-01-17 06:18
>I honestly don't how your first screenshot was able to render in MSAA without the glitched black line, but I'm pretty sure that it is "wrong" according to our OpenGL renderer.
The first screenshot was before 0dab591, so technically it wasn't clearing the fog so I can replicate it by doing if (this->_enableFog && !this->_enableMultisampledRendering) and have visually correct fog rendering but as you say, not clearing the fog is not correct behavior.
