### ISSUE TITLE
Multi thread support for AVI dumping

### ISSUE THREAD

**Issue by fintogive** [TASVideos/desmume#105] opened 2017-10-14 08:16 UTC
The built in AVI dumper currently uses a single core/thread to render a video. 

Since the introduction of HD prescale resolutions up to x16. AVI dumping can be quite slow on a single thread with most of today's computers having multi core cpus it would be a great improvement in speed to support two cores instead of one for avi dumping,

**Comment by zeromus** [comment] 2017-10-23 19:52
AVIStreamWrite is still in the main thread; that's what does the encoding (and disk writing)--it could be kicked to another thread still

**Comment by rogerman** [comment] 2018-02-26 00:28
Try commit cbe4717. AVIStreamWrite() for both video and audio streams are now called together on a separate thread, and so AVI recording should be significantly faster now.

However, know that the current AVI recording code will only be, at most, 1 frame behind the emulation. This means that a disk bottleneck or a CPU bottleneck will show itself immediately. But hopefully, the performance improvement should be sufficient for now.

**Comment by fintogive** [comment] 2018-02-26 02:12
working much better! got nearly double frame rate at x3 resolution dumping to external SSD via usb 3.0 using langrith lossless codec

**Comment by rogerman** [comment] 2018-02-26 02:28
Excellent! I'm glad it's working out for you! Since the multithreading goal has been met, I think it's safe to say that we can close this one out.

In the future, it may be possible to rework the buffering of frames so that AVI recording isn't as sensitive to temporary lag spikes -- maybe buffering one second worth of frames (60 frames) or something like that. This would consume an enormous amount of memory at the higher resolutions, but it would make recording a little smoother. I'll leave this note here as a future reminder for anyone that may want to tackle this.

@fintogive, your video of the F-Zero texture hack for Mario Kart DS... was an incredible sight to behold. 😄

**Closed by rogerman** 2018-02-26 02:28 UTC
Labels: enhancement

**Comment by fintogive** [comment] 2018-02-26 02:36
Yes i agree.  Thank you for improving that it really needed it! ill have to try the recording on my threadripper 16C 32T cpu next with M2 SSD.

You saw that? thank you! :P  thats was rendered on a surface pro 2017 i7 at x11 resolution with 24 bit color.  it was rendering 1 frame a secound at that resolution.  
Your welcome to use that video as a demonstration of desmume latest features on the next stable release if you want to.

**Comment by rogerman** [comment] 2018-02-26 03:09
Oh yeah, I forgot to mention this in the commit cbe4717 notes, and so I'll mention it here since you reminded me: The framebuffer conversion operation has been expanded to use a maximum of 32 threads, up from a maximum of 16 threads. This means that your Threadripper CPU should be able to take advantage of that change.

In general, all operations that are maxing out at 16 threads are being expanded to 32 threads due to newer CPUs like the Threadripper. This has already been done with SoftRasterizer renders, and now has been done for AVI framebuffer color conversions.

**Comment by fintogive** [comment] 2018-02-26 03:36
oh dang! thinking ahead there nice! :D

**Comment by fintogive** [comment] 2018-02-26 13:01
i can dump at near full speed at x4 and around 45fps at x5.  and x16 4fps

**Comment by rogerman** [comment] 2018-03-02 21:40
Since my mind was still on the subject, I just went ahead and implemented the better buffering scheme to reduce lag spikes. See commit 8763a61 for more details. DeSmuME's AVI recorder will buffer up to 1.5 GB worth of frames or 180 frames (or 3 seconds worth of frames), whichever is less. I think 1.5 GB of RAM consumption is reasonable for this application, since I'm assuming that video editors are going to have a decent amount of RAM on their machines.

Also while I was at it, the multithreading has been improved to synchronize less often to the main thread. This allows for better recording performance in general.

After commit 8763a61, I don't see any improvements to AVI recording functionality under the current system. It is now as good as it's going to get. The only way to improve recording at this point is to move to beyond the ancient Video for Windows API.

**Comment by rogerman** [comment] 2018-03-03 00:12
Err... forget commit 8763a61. Try using commit e825cdd instead, which fixes a regression in AVI recording.

**Comment by fintogive** [comment] 2018-03-03 02:00
i just tried it it seems to be working even better imo.  A lot smoother rendering.  what would be the minimal ram requirements by the way?  all my computers have 16gb of ram and up.  like 8gb?  cause i was thinking if the computer doesn't have the required ram that it has a way to fall back so it doesn't chew the ram up.

**Comment by rogerman** [comment] 2018-03-03 03:08
For the emulation by itself, the minimum RAM requirement is what is listed on our FAQ, which is 2 GB. However, this means that your computer is running virtually barebones (like right after a fresh OS install) while running DeSmuME at its lowest possible settings. That is why we recommend 4 GB of RAM for the host machine, so that users can take advantage of some of DeSmuME's more advanced features.

AVI recording is one of those advanced features that is not taken into account when estimating the minimum RAM requirements. It would be safe to say that if you do AVI recording, then you should have the recommended 4 GB of RAM, plus an additional 1.5 GB to account for the potential max. RAM consumption of AVI recording. If you are recording very large HD frames, then expect to add an additional 0.5 GB to account for the size of the internal framebuffers.

**In short, the recommended RAM for the AVI recording user is 6 GB.** I believe that this is very reasonable by today's standards. People who do a lot of video editing work tend to have way more than 6 GB on their machines. If you find that AVI recording is consuming too much RAM (or maybe you want to increase the RAM usage for even better stability), then you can build your own copy of DeSmuME and change the constant MAX_PENDING_BUFFER_SIZE to a different value. There is a strong possibility that this will become a user-adjustable value in the future.

Of course, another option is to simply record smaller video frames -- that will significantly lower your RAM usage. For example, recording at 4x size will consume this much RAM:
* Each frame consume 4.5 MB
* AVI recording will buffer a maximum of 180 frames
* Therefore, 4.5 MB * 180 = 810 MB

And then if you record at 2x:
* Each frame consumes 1.125 MB
* Therefore, 1.125 MB * 180 = 202.5 MB

**Comment by fintogive** [comment] 2018-03-03 03:13
I see well in that case id play it safe and just to minimal 8GB ram since most computer do 8gb today. i do video editing minimal is 16GB ram but personally i do 32GB since i use premier pro and after effects.

**Comment by rogerman** [comment] 2018-03-03 03:34
I think that users should be smart enough to know that recording large HD video frames is going to consume more RAM than recording small video frames. Or that simply not doing recording at all will eliminate the additional RAM consumption entirely.

Or maybe the user can record at 1x, just like in v0.9.11:
* Each frame consumes 288 KB
* Therefore, 288 KB * 180 = 50.626 MB

Remember that the additional RAM consumption for AVI recording only takes effect when the user is actually recording. A lot of users never use DeSmuME's AVI recording feature. So I think the 2 GB minimum RAM requirement (and 4 GB recommended) still holds true today. DeSmuME's RAM usage can be (relatively) low if you don't use any of its bells and whistles.

In reality, my main concern when I was writing this code was that having 1.5 GB RAM limit was too low for you video editors! I would think that a video editor with 16 GB of RAM would want to raise this limit in order to maximize their recording stability!

However, I also needed to be aware that this code is supposed to run on 32-bit as well as 64-bit machines, so I held back the limit to 1.5 GB. Maybe the limit can be different depending on if the user is running 32-bit or 64-bit.

I don't see myself raising the maximum buffered frames, since 180 frames is 3 seconds worth of frames, and 3 seconds is really a long time to buffer. However, there is also a strong possibility that this will become a user-adjustable value in the future.
