### ISSUE TITLE
Crashing on Mac

### ISSUE THREAD

**Issue by dillypilly888** [TASVideos/desmume#397] opened 2020-11-18 19:01 UTC
When loading 2019/03/18 – git#be2735b Mac Cocoa (x86, x86-64) download the emulator crashes the moment it opens and 0.9.11 shows no video

**Comment by zeromus** [comment] 2020-11-18 19:07
see #321. 
it's possible that git version is afflicted by #335 
Either way, it's a dupe of one of those two issues.

**Closed by zeromus** 2020-11-18 19:07 UTC
