### ISSUE TITLE
fast forward not working well when gpu scaling enabled (and dual screen 3d?)

### ISSUE THREAD

**Issue by zeromus** [TASVideos/desmume#244] opened 2019-01-11 02:03 UTC
on windows, in pokemon white, in a town at the start, with gpu scaling 2x, the top screen will cut out entirely when fast forwarding.
http://forums.desmume.org/viewtopic.php?pid=27417#p27417

**Comment by Jules-A** [comment] 2019-01-11 02:43
It also occurs when you enable frameskip and every time it skips.

**Comment by rogerman** [comment] 2019-01-11 06:11
There was a regression from commit abc0649 that could cause graphical glitches when running custom resolutions on multicore CPU systems.

Specifically, the bug was caused by the asynchronous clearing thread being started regardless of frameskip being enabled or disabled. However, the async clearing thread would only finish if frameskip was disabled. The bug was fixed by allowing the async clearing thread to start ONLY when frameskip is disabled, which is the intended behavior.

Commit f5d90a7 resolves this particular bug. Hopefully, that bug fix is enough.

**Comment by rogerman** [comment] 2019-01-12 20:51
Confirmed fixed by the user. See the forum link in the OP for more details.

**Closed by rogerman** 2019-01-12 20:51 UTC
