### ISSUE TITLE
[OpenGL] Zelda - Spirit Tracks - Intro Slow Down

### ISSUE THREAD

**Issue by Papermanzero** [TASVideos/desmume#89] opened 2017-08-05 12:10 UTC
Start Spirit Tracks and watch the very first intro until Zelda in her ghost form appears (during the train ride) The emulator is falling back to 5 FPS.

I used the latest commit.

**Comment by rogerman** [comment] 2017-08-05 17:07
The Legend of Zelda: Spirit Tracks intro sequence is an extremely notorious sequence for causing massive texture thrashing to occur. This is the reason for the slow down.

Texture thrashing is caused by three issues:
1. All new loaded textures must be deposterized (if Texture Deposterize is enabled)
2. All new loaded textures must be upscaled (if Texture Scaling is higher than 1x)
3. For the OpenGL renderer, all new textures must be transferred from the CPU to the GPU

There is absolutely nothing the end user can do about this. The best thing the end user can do is to avoid these three points of slow down by doing the following:
1. Turn off Texture Deposterize
2. Reduce Texture Scaling down to 1x
3. Use SoftRasterizer

In the future, there may be an optimization for the OpenGL renderer to do some on-GPU texture unpacking, which would then lead to on-GPU texture filtering. This would remove the slow down for deposterization and upscaling. However, you absolutely have to do a CPU-to-GPU texture transfer at some point, and so this slow down will ALWAYS continue to exist.

Closing, since this is an already known issue, and because there already is an existing workaround.

**Closed by rogerman** 2017-08-05 17:07 UTC
