### ISSUE TITLE
SM64DS 3D OpenGL Render Issue

### ISSUE THREAD

**Issue by wildgoosespeeder** [TASVideos/desmume#17] opened 2016-12-16 06:09 UTC
SoftRasterizer:
![1](https://cloud.githubusercontent.com/assets/18543809/21253373/c9418b68-c323-11e6-85de-cbeff7b183a6.png)
OpenGL 3.2:
![2](https://cloud.githubusercontent.com/assets/18543809/21253374/c946ad28-c323-11e6-8b79-e3abaede1df7.png)

SoftRasterizer is closer to the real hardware in this case. The colors are off in OpenGL.

**Comment by rogerman** [comment] 2016-12-16 06:13
You'll need to do better than that. Please provide more details about your specific issue instead of simply providing screenshots that can be ambiguously interpreted.

So some questions:
- What rendering issue are you having a problem with?
- What version of DeSmuME are you using?
- What 3D rendering settings are you using?

**Comment by zeromus** [comment] 2016-12-16 06:13
Fog. It's nearly impossible to get right on opengl. Unless there's some other difference you didn't articulate

Steps to take compatible screenshots
1. Savestate
2. Frame advance a few N times
3. Screenshot
4. Switch renderer
5. Loadstate
6. Frame advance same N times
7. Screenshot

**Comment by rogerman** [comment] 2016-12-16 06:16
Well yeah, I saw the missing fog in the OpenGL screenshot, but that may not be an issue in v0.9.11, since that version is already known to not support fog rendering in the OpenGL renderer.

But in the current code, fog is fully supported in the OpenGL renderer, but it may be turned off in his 3D settings, so again, who knows what his problem actually is.

**Comment by wildgoosespeeder** [comment] 2016-12-16 06:18
@rogerman 
* Screenshots speak for themselves
* 0.9.11
* Just said.

@zeromus 
Doesn't matter that much in this case. Just get to "Bowser in the Fire Sea" and face bowser to switch rendering engines.

@rogerman 
So this OpenGL bug is known and is already fixed for the future release 0.9.12?

**Comment by rogerman** [comment] 2016-12-16 06:26
@wildgoosespeeder 
- No, the screenshots do not necessarily speak for themselves. There are more differences in the screenshots than just the lack of fog.
- In v0.9.11, it is an already known issue that fog is not supported in the OpenGL renderer. This has been rectified in the current version of the code base.
- You provided zero details about your 3D rendering settings. Have you seen the panel? There are a lot more options than just picking your rendering engine.

As the bug reporter, it is your job to provide specific details about your issues so that we can understand what you're saying. We're not psychic.

Closing, since this issue has been resolved in r5166.

**Closed by rogerman** 2016-12-16 06:26 UTC

**Comment by zeromus** [comment] 2016-12-16 06:31
I was teaching you how to improve your analytical methods. Bug reports from people unwilling to improve their analytical methods are tiresome.

**Comment by wildgoosespeeder** [comment] 2016-12-16 06:32
@rogerman @zeromus 
What other information do you need?

**Comment by rogerman** [comment] 2016-12-16 06:37
We knew exactly what your issue was from the very start. It was obvious.

But it's really disrespectful to submit a bug report to the developers when it is also clearly obvious that you did zero research on how you could resolve the bug on your own. Because if you submitted a bug report that wasn't as obvious, then we would've been wasting a bunch of time playing 20 questions instead of actually getting real work done.

You could have looked at this: http://wiki.desmume.org/index.php?title=Faq#OpenGL_Renderer

Or you could have tried a nightly build from here for testing: http://desmume.org/download/

We do work to fix your issues, so you need to also do work in reporting them.

**Comment by wildgoosespeeder** [comment] 2016-12-16 08:02
@rogerman 
Zero research? My research pointed me to use SoftRasterizer instead of OpenGL. I just reported just to be sure the bug gets fixed (which it has in r5166).

Instead of getting into this discussion with me, you could have said _oh, that's been fixed for release 0.9.12 and this will be closed_ and everything would have been dandy.

I know how a bug reports work. I gave as much relevant information as I could. I can understand vagueness, but this bug report is somewhat descriptive. Probably not as descriptive as you probably hoped, but not too vague either.

**Comment by rogerman** [comment] 2016-12-16 09:02
> Zero research? My research pointed me to use SoftRasterizer instead of OpenGL to get correct rendering. I just reported just to be sure the bug gets fixed at some point (which it has in r5166).

My point exactly. That's not research. All you did was just a quick observation comparing two different 3D renderers. If you did actual research, you would have found more information about the fog issue on our FAQ or from our nightlies, and that information would have answered your issue right there.

> Instead of getting into this discussion with me, you could have said oh, that's been fixed for release 0.9.12 and this thread will be closed and everything would have been dandy.

Because you're acting without any respect, which makes you come off like some spoiled pretentious brat. Try using better manners. Acting like a condescending prick towards the developers who are trying to serve your needs also doesn't help. And then on top of all of that, you edit your posts after we respond to your posts in some childish effort to discredit what zeromus and I are saying whilst protecting your own bruised ego at the same time. All of these behaviors end up hurting your integrity as a human being.

> I know how a bug reports work. I gave as much relevant information as I could. I can understand vagueness, but this bug report is somewhat descriptive. Probably not as descriptive as you probably hoped, but not too vague either. I do realize I forgot to tell you what version I was using (I usually don't), but everything else was there right from the start. Hey, if you want to avoid as much vagueness as possible, how about a pre-loaded template when new issue is clicked?

No, you do not know how bug reports work, which is why we're trying to teach you how they actually do work. For the record, you named your issue "SM64DS 3D OpenGL Render Issue" and provided two naked screenshots with no additional text other than "SoftRasterizer" and "OpenGL 3.2" (this is all per your true original post, not the edited one that you made to discredit me and to make yourself look like you did the right thing all along). A real bug report cites actual details of the issue and steps to reproduce. If you really knew how bug reports work, then you wouldn't need a preloaded template.

> So this OpenGL bug is known and is already fixed for the future release 0.9.12? If so, just checking and you can close this. This might be related to other wrong effects, such as dark transparent clouds in World 7 of New Super Mario Bros. and too dark HUD at any level select screen for Super Princess Peach.

In response to this post (which you also edited after the fact), the issues in New Super Mario Bros. and Super Princess Peach are completely unrelated to fog rendering. Those issues are due to the OpenGL renderer not being able to emulate a special NDS blending condition (but SoftRasterizer can emulate this). This issue is not easy to fix, and if it were fixed, it would probably result in a massive performance hit to the OpenGL renderer.

**Comment by wildgoosespeeder** [comment] 2016-12-16 21:22
@rogerman 
So what I am getting at is its my fault the emulator isn't working and it is my fault for not meeting your unclear standards in bug reporting? Way to go preaching about respect where you have no respect for the person trying to express concern as best as they could about a bug they noticed. Such irony here. You and zeromus pretty much proved to me how much of a wasted time it is to even report bugs about your emulator. All this over me trying to show there was a bug in OpenGL 3.2 renderer that I didn't know. You gave me that information and showed your contempt towards me and probably others. I didn't ask for the latter.

**Comment by zeromus** [comment] 2016-12-16 21:30
There are specific reasons we have no respect for you. I've given you one. Here's another:
"What rendering issue are you having a problem with?" -> "Screenshots speak for themselves"

If you want to earn respect, accept your spankings, and get back to work.  You know what we're not doing while we're arguing with you? Working on desmume.

**Comment by wildgoosespeeder** [comment] 2016-12-16 21:35
@zeromus 
OK, how am I supposed to know the thing I am trying to point to is "fog effects"? Not everyone knows that effect to be fog. It could be called a "color filter". Also, what is the first thing that jumps out at you is different about those screenshots?

You could be working on DeSmuME. Through the internet, I can't prevent you doing anything. You are choosing to berate me. You are prioritizing that to be more important than working on DeSmuME.
