### ISSUE TITLE
Mario Kart DS shadow glitch on 150 cc mirror tracks. 

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#21] opened 2016-12-30 08:49 UTC
This bug only happens on **Grand Prix 150 cc mirror tracks**, and I suspect the shadow is filter out by back face culling.

![mario kart ds](https://cloud.githubusercontent.com/assets/8726272/21561958/d65e9ac0-ceae-11e6-8854-fe8d54522ee9.jpg)

steps to reproduce this bug:
(1) download latest test build from official web site.
(2) change renderer to OpenGL 3.2
(3) run Mario Kart DS
(4) select GRAND PRIX mode 150 cc mirror tracks

======
code related to this bug
======
`Render3DError OpenGLRenderer_3_2::SetupPolygon(const POLY &thePoly)
{
	const PolygonAttributes attr = thePoly.getAttributes();
	
	// Set up depth test mode
	static const GLenum oglDepthFunc[2] = {GL_LESS, GL_EQUAL};
	glDepthFunc(oglDepthFunc[attr.enableDepthEqualTest]);
	
	// Set up culling mode
	if ( (attr.polygonMode == POLYGON_MODE_SHADOW) && (attr.polygonID != 0) )
	{
		glEnable(GL_CULL_FACE);
		glCullFace(GL_BACK);
	}
        else
        {
            ......
        }
`
disable OpenGL face culling for shadow polygons should fix this bug.

Mario Kart DS save file:
[Mario Kart DS (USA).zip](https://github.com/TASVideos/desmume/files/678455/Mario.Kart.DS.USA.zip)

**Comment by rogerman** [comment] 2016-12-30 09:12
Cannot reproduce this bug using the 2016/12/28 nightly build (based on commit ae37e12) for Cocoa, Windows 32-bit, or Windows 64-bit. The shadows appear perfectly fine for all builds when using OpenGL 3.2.

We'll need more information to troubleshoot. Please provide your driver version and renderer (these will be listed under Driver Info for "Version" and "Renderer" in the console. We will also need the ROM serial, and we will need to know if you are using any cheats.

**Comment by ppsspp-gamer** [comment] 2016-12-30 09:41
> Please notice:
>  This bug only happened on 150 CC mirror tracks.
> 50 cc, 100 cc, 150 cc didn't have this issue.
> That's why I also attached my save file for debug.


=======================
driver info and rom serial
=======================
DeSmuME 0.9.12 git#ae37e12 x64-JIT SSE2
- compiled: Dec 14 2016 17:22:06

DirectX Input:
   - gamecontrol successfully inited: Controller (XBOX 360 For Windows)
Microphone successfully inited.
DeSmuME 0.9.12 git#ae37e12 x64-JIT SSE2
Attempting change to 3d core to: OpenGL 3.2
WGL OpenGL mode: hardware
OpenGL: Successfully created shaders.
OpenGL: Successfully created postprocess shaders.
OpenGL: Successfully created FBOs.
OpenGL: Successfully created multisampled FBO.
OpenGL: Renderer initialized successfully (v3.2.0).
[ Driver Info -
    Version: 4.5.0 NVIDIA 376.09
    Vendor: NVIDIA Corporation
    Renderer: GeForce GTX 760M/PCIe/SSE2 ]
GL display context pixel format: 8

ROM game code: AMCE
ROM crc: D47555BE
ROM serial: NTR-AMCE-USA
ROM chipID: 00001FC2
ROM internal name: MARIOKARTDS
ROM developer: Nintendo
Found in game database by Serial/CRC:
        * ROM serial:           AMCE
        * ROM save type:        FLASH 2Mbit
        * ROM crc:              D47555BE

Slot1 auto-selected device type: Retail MC+ROM
Slot2 auto-selected device type: None (0xFF)
BackupDevice: size = 2 Mbit
CPU mode: JIT
JIT: max block size 15 instruction(s)
ARM7 BIOS load: OK.
ARM9 BIOS load: OK.
Already decrypted.
Firmware:
- path: firmware.bin
- size: 262144 bytes (32 Mbit)
- CRC : 0xABBB
- header:
   * size firmware 0
   * ARM9 boot code address:     0x00000180
   * ARM9 boot code RAM address: 0x021F0000
   * ARM9 unpacked size:         0x00000014 (20) bytes
   * ARM9 GUI code address:      0x000183B0

   * ARM7 boot code address:     0x000001A0
   * ARM7 boot code RAM address: 0x0380F800
   * ARM7 WiFi code address:     0x0000F5B0
   * ARM7 unpacked size:         0x00000110 (272) bytes

   * Data/GFX address:           0x000002C0

Flashme:
- header:
   * ARM9 boot code address:     0x000323B0
   * ARM9 boot code RAM address: 0x0231FE00
   * ARM9 unpacked size:         0x00010F24 (69412) bytes

   * ARM7 boot code address:     0x00029FA8
   * ARM7 boot code RAM address: 0x037FA600
   * ARM7 unpacked size:         0x0000B1EC (45548) bytes
Loading d:\rom\nds\Mario Kart DS (USA).nds was successful
Emulation unpaused
 * SPU2 > Underrun compensation (3 packets buffered)

**Comment by rogerman** [comment] 2016-12-30 10:28
Ah, I see. 150cc MIRROR is different from just the plain 150cc I tested. So with the save file you provided, I was able to reproduce the bug.

The forced backface culling, which is what is causing this shadow bug, is also being performed in SoftRasterizer, which is why I also included it in the OpenGL renderer when I reworked the code. Therefore, you will see this same bug happen for ALL 3D renderers.

According to GBATEK, there is no need for 2nd-pass shadow polygons to have forced backface culling, instead suggesting that these polygons should respect the culling mode set by the game. Changing SetupPolygon() to reflect this idea does fix the shadow bug.

However, I am still curious about why SoftRasterizer did the forced backface culling for 2nd-pass shadow polygons in the first place. (SoftRasterizer was created long before my time.) This issue will be closely reviewed as I gather some more information about it.

**Comment by zeromus** [comment] 2016-12-30 17:04
All I have to add other than what's in those comments is that gbatek is more confident about shadows than it used to be, and I'm not confident we've ever solved it correctly. The code right now is based on tests and guesses and I don't like the results. Maybe with more tests and confidence from gbatek you can hammer it out more correctly.

**Comment by rogerman** [comment] 2016-12-30 18:24
After some testing with The Wizard of Oz: Beyond the Yellow Brick Road, I've determined that there are clear differences with how SoftRasterizer and OpenGL handle shadow polygons.

If you disable forced backface culling in OpenGL, shadow polygons seem to render correctly in all cases.

But if you disable this in SoftRasterizer, then shadow polygons render correctly in Mario Kart, but not in TWoO:BtYBR. I'm almost positive that this is a clearly hack, originating back from r2706, designed to fix shadows in TWoO:BtYBR. Of course, enabling forced backface culling in SoftRasterizer helps TWoO:BtYBR, but hurts Mario Kart.

So I'm leaning towards the side of GBATEK being correct in this case. The forced backface culling should be removed from all renderers. However, it will temporarily remain in SoftRasterizer until we can determine the underlying issues that are causing SoftRasterizer to fail.

**Comment by rogerman** [comment] 2016-12-30 19:11
Fixed in commit cf8f021.

After some discussion with @zeromus and some additional testing with other games, we're more confident that removing forced backface culling is the correct decision. This commit reflects doing just that in the OpenGL renderer.

But we will need to do the same thing in SoftRasterizer as well, but only after we rework shadow polygon handling to be more correct. For our own notes, we will need to test against the following test cases where removing forced backface culling will affect things:

1. The Wizard of Oz: Beyond the Yellow Brick Road -- shadows under Dorothy and Toto
2. Kingdom Hearts Re:coded -- shadow under Sora
3. Golden Sun: Dark Dawn -- shadow under the main character
4. Mario Kart DS -- shadows under Karts during Kart select for 150cc MIRROR

**Closed by rogerman** 2016-12-30 19:11 UTC
Labels: bug

**Comment by zeromus** [comment] 2017-01-08 21:31
fixed in softrasterizer by a5b4df2

**Comment by ppsspp-gamer** [comment] 2017-01-17 11:50
nice fix.
