### ISSUE TITLE
Assertion failure in Water Horse Legend Of The Deep

### ISSUE THREAD

**Issue by zaxcav** [TASVideos/desmume#39] opened 2017-02-10 21:34 UTC
When running desmume (gtk frontend) commit 241f50e compiled under Linux Mint 18.1 the following assertion failure is encountered in the first level of Water Horse Legend Of The Deep:

> desmume: ../../matrix.cpp:287: void MatrixStackLoadMatrix(MatrixStack*, size_t, const s32*): Assertion `pos<31' failed.

Looking quickly at matrix.cpp, it looks like the assert _may be_ off by one and should be:
`assert(pos<=31);`

My reasoning here is that where this is called in gfx3d.cpp, the size_t argument is masked with 31.

Adjusting this assert (and another identical assert in matrix.cpp on line 276) and recompiling results in no further assertion failures in Water Horse.

But I don't otherwise know anything about the code, so the developers should confirm whether this is correct or not.

**Comment by zeromus** [comment] 2017-02-11 01:02
It's not as you suspect (the mask is just to prevent memory from getting stomped) but this additional test case will be helpful in straightening out the logic which does seem to be confused.

**Comment by zeromus** [comment] 2017-02-11 14:18
Uhhhhhhh how do I make this happen? I walked on some grass and then walked in a sparkling door and now a manatee is in a pool and it seems like the 2nd level, and I never saw the matrix assert flake out

**Comment by zaxcav** [comment] 2017-02-11 19:33
Yes, the manatee in the barrel of water is the 2nd level.

The assert failure happens for me in the first level just walking around with the boy. Sometimes almost immediately, other times after some time. I can't identify any obvious game conditions that cause it.

It may be ROM version specific.
In this case here's the info of the ROM dump I tried:

> ROM game code: YWHP
> ROM serial: NTR-YWHP-EUR
> ROM chipID: 00000FC2
> ROM internal name: WATERHORSE
> ROM developer: Unknown

Is there any debugging output I can turn on that could help?

**Comment by zeromus** [comment] 2017-02-11 22:48
OK, I made it happen. Maybe it's one of the spies that does it. I've inspected it further, and our code is definitely dodgy. I think I can fix this.

**Comment by zaxcav** [comment] 2017-02-21 21:08
@zeromus I won't pretend to understand any of what went into fixing this. Great work.
I've bought 3 games this last week alone after trying them out first with desmume - it's a very useful tool.
Reporting this issue was a small way I could contribute to the project. Many thanks for your effort getting it resolved.

**Comment by rogerman** [comment] 2017-02-22 05:29
Regression from commit 1cc22ae.

Now there is a coloring issue in the title screen of Super Mario 64 DS. You can see similar coloring issues with Yoshi as your playing the game.
![smario64ds_coloringbug](https://cloud.githubusercontent.com/assets/6055122/23198464/9cb44d90-f87c-11e6-9ca4-11db393e3828.png)

**Comment by zeromus** [comment] 2017-02-22 06:26
oops. Thought I checked that. Well, good news, that was able to prove I can make it even simpler than it was before. The code's much prettier now!

**Comment by zaxcav** [comment] 2017-02-22 19:24
@zeromus Haha. Indeed, that was **not** one of the games I bought. As I said, desmume is a very useful tool ... for sorting the gems from the rubbish, to find out what is worth spending money on.

**Comment by rogerman** [comment] 2017-02-22 23:05
I can confirm that the graphical issues in Super Mario 64 DS are fixed in commit b553ff9.

But we gotta keep this one open. Commit 1cc22ae also causes Nanostray 2 to assert at the beginning of the first level at MatrixStackGetPos().

**Comment by rogerman** [comment] 2017-02-22 23:21
Another test case -- In Advance Wars: Dual Strike, attacking an enemy unit and bringing up the unit combat animation screen makes causes the same assert in MatrixStackGetPos(). The assert occurs because pos == stack->size.

**Comment by rogerman** [comment] 2017-02-23 23:47
After commit 7031bd9, it seems like the various 3D games I've tried won't set off the assert, so I think its safe to close this one out now.

**Closed by rogerman** 2017-02-23 23:47 UTC
